name: "ci-cd pipeline for auth frontend preprod"

on:
    workflow_dispatch:

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "21"
            
            - name: "check node installation"
              run: |
               node --version
                npm --version

            - name: Install dependencies
              run: npm install

            - name: "list all directories"
              run: ls 

            - name: Build
              run: npm run build

            